version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  node_exporter:
    build:
      context: node_exporter
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.37.9
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9091:9090
    depends_on:
      - node_exporter
    links:
      - node_exporter

  # grafana:
  #   image: grafana/grafana
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ./grafana/provisioning/:/etc/grafana/provisioning/
  #   env_file:
  #     - ./grafana/config.monitoring
